# Nom de l'application
spring.application.name=demo

# Configuration de la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/basedonne_pfe?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration HikariCP (pool de connexions)
spring.datasource.hikari.pool-name=HikariPool-1
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
jwt.secret=4EUSmM3eQkGZjna52LnfX+52tCMlDN7U7K3s2eReAcM
jwt.expiration=86400000
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

logging.level.com.example.demo=DEBUG
debug=true
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=TRACE
logging.level.org.springframework.transaction=TRACE
